# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json

configuration:
  pageTitle: "\U0001F4DA Study Notes"
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: zh-CN
  baseUrl: LeafDot37.github.io/notes-share
  ignorePatterns:
    - .obsidian
    - .claudian
    - .git
    - .github
    - node_modules
    - public
    - private
    - "*.pdf"
  defaultDateType: created
  theme:
    cdnCaching: true
    typography:
      header: Schibsted Grotesk
      body: Source Sans Pro
      code: JetBrains Mono
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        textHighlight: "#fff23688"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        textHighlight: "#b3aa0288"

layout:
  head:
    - component: Head
  footer:
    - component: Footer
      links:
        GitHub: "https://github.com/LeafDot37/notes-share"
  page:
    beforeBody:
      - Breadcrumbs
      - ArticleTitle
      - ContentMeta
      - TagList
    left:
      - PageTitle
      - MobileOnly(Spacer)
      - Search
      - Darkmode
      - DesktopOnly(Explorer)
    right:
      - Graph
      - DesktopOnly(TableOfContents)
      - Backlinks
  list:
    beforeBody:
      - Breadcrumbs
      - ArticleTitle
      - ContentMeta
    left:
      - PageTitle
      - MobileOnly(Spacer)
      - Search
      - Darkmode
      - DesktopOnly(Explorer)
    right: []

plugins:
  - source: QuartzFrontMatter
  - source: CreatedModifiedDate
    options:
      priority:
        - frontmatter
        - filesystem
  - source: SyntaxHighlighting
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
  - source: ObsidianFlavoredMarkdown
    options:
      enableInHtmlEmbed: false
  - source: GitHubFlavoredMarkdown
  - source: TableOfContents
  - source: CrawlLinks
    options:
      markdownLinkResolution: shortest
  - source: Description
  - source: Latex
    options:
      renderEngine: katex
  - source: RemoveDrafts
  - source: AliasRedirects
  - source: ComponentResources
  - source: ContentPage
  - source: FolderPage
  - source: TagPage
  - source: ContentIndex
    options:
      enableSiteMap: true
      enableRSS: true
  - source: Assets
  - source: Static
  - source: NotFoundPage
  - source: Explorer
  - source: Graph
